# exp setting
exp_name: 'MTR_AV2_JEPA_Linear_Probing_2' # name that will be used in wandb
ckpt_path: null # checkpoint path, used for evaluation
seed: 42 # random seed
debug: False # debug mode, will use cpu only
devices: [ 0 ] # gpu ids

# data related
load_num_workers: 8 # number of workers for loading data
train_data_path: [ "/home/erik/ssd2/datasets/scenarionet_argoverse2_train"] # list of paths to the training data VOD: /home/erik/raid/datasets/vod/scenarionet_vod_train NUSC: /home/erik/ssd2/datasets/scenarionet_nusc_train VOD Pose: /home/erik/raid/datasets/vod/scenarionet_vod_train_with_poses nuScenes: /home/erik/ssd2/datasets/scenarionet_nusc_train_1_8
val_data_path: [ "/home/erik/ssd2/datasets/scenarionet_argoverse2_val" ] # list of paths to the validation data VOD: /home/erik/raid/datasets/vod/scenarionet_vod_val NUSC: /home/erik/ssd2/datasets/scenarionet_nusc_val VOD Pose: /home/erik/raid/datasets/vod/scenarionet_vod_val_with_poses nuScenes: /home/erik/ssd2/datasets/scenarionet_nusc_val_1_8
max_data_num: [ 100000] # maximum number of data for each training dataset
starting_frame: [ 0] # history trajectory starts at this frame for each training dataset
past_len: 20 #11 # history trajectory length, 2.1s #VOD: 6 NUSC: 21 AV2: 20
future_len: 30 #80 # future trajectory length, 6s #VOD: 30 NUSC: 60 AV2: 30
object_type: [ 'VEHICLE' , 'PEDESTRIAN', 'CYCLIST'] # object types included in the training set
line_type: [ 'lane','stop_sign','road_edge','road_line','crosswalk','speed_bump' ] # line type to be considered in the input
masked_attributes: [] #[ 'z_axis', 'size' ] # attributes to be masked in the input
trajectory_sample_interval: 1 # sample interval for the trajectory
only_train_on_ego: False # only train on AV
center_offset_of_map: [ 30.0, 0.0 ] # center offset of the map
use_cache: True # use cache for data loading
overwrite_cache: True # overwrite existing cache
store_data_in_memory: False # store data in memory

POSES: False
JEPA: True

# official evaluation
nuscenes_dataroot: '/home/erik/NAS/publicdatasets/nuscenes' # path to the nuscenes dataset
vod_dataroot: '/home/erik/raid/datasets/vod/View_of_Delft_dataset_PUBLIC/view_of_delft_prediction_PUBLIC/vod_official'
eval_nuscenes: False # whether to evaluate with nuscenes evaluation tool
eval_waymo: False # whether to evaluate with waymo evaluation tool
eval_vod: False # whether to evaluate with vod evaluation tool

defaults:
  - method: autobot